# Generated by Django 3.0 on 2019-12-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infinitive',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('frequency', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('infinitive', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('translation', models.CharField(max_length=50)),
                ('past_participle', models.CharField(max_length=30)),
                ('present_ich', models.CharField(max_length=30)),
                ('present_du', models.CharField(max_length=30)),
                ('present_er', models.CharField(max_length=30)),
                ('present_wir', models.CharField(max_length=30)),
                ('present_ihr', models.CharField(max_length=30)),
                ('present_sie', models.CharField(max_length=30)),
                ('perfect_ich', models.CharField(max_length=30)),
                ('perfect_du', models.CharField(max_length=30)),
                ('perfect_er', models.CharField(max_length=30)),
                ('perfect_wir', models.CharField(max_length=30)),
                ('perfect_ihr', models.CharField(max_length=30)),
                ('perfect_sie', models.CharField(max_length=30)),
                ('past_ich', models.CharField(max_length=30)),
                ('past_du', models.CharField(max_length=30)),
                ('past_er', models.CharField(max_length=30)),
                ('past_wir', models.CharField(max_length=30)),
                ('past_ihr', models.CharField(max_length=30)),
                ('past_sie', models.CharField(max_length=30)),
            ],
        ),
    ]
