# Generated by Django 3.0 on 2019-12-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verb',
            new_name='ConjugatedVerb',
        ),
    ]
