# Generated by Django 3.0 on 2019-12-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugator', '0002_auto_20191205_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConjugatedVerb',
        ),
        migrations.AddField(
            model_name='infinitive',
            name='past_du',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='past_er',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='past_ich',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='past_ihr',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='past_participle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='past_sie',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='past_wir',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='perfect_du',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='perfect_er',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='perfect_ich',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='perfect_ihr',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='perfect_sie',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='perfect_wir',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='present_du',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='present_er',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='present_ich',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='present_ihr',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='present_sie',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='present_wir',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='translation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
