# Generated by Django 3.0 on 2019-12-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugator', '0003_auto_20191205_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infinitive',
            new_name='Verb',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='name',
            new_name='infinitive',
        ),
    ]
