# Generated by Django 3.0 on 2019-12-07 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugator', '0004_auto_20191205_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verb',
            name='past_du',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='past_er',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='past_ich',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='past_ihr',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='past_sie',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='past_wir',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='perfect_du',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='perfect_er',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='perfect_ich',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='perfect_ihr',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='perfect_sie',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='perfect_wir',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='present_du',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='present_er',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='present_ich',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='present_ihr',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='present_sie',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='present_wir',
        ),
    ]
