# Generated by Django 3.0 on 2019-12-07 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugator', '0005_auto_20191207_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='present_participle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Conjugation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=30)),
                ('tense', models.CharField(max_length=30)),
                ('ich', models.CharField(blank=True, max_length=30)),
                ('du', models.CharField(blank=True, max_length=30)),
                ('er', models.CharField(blank=True, max_length=30)),
                ('wir', models.CharField(blank=True, max_length=30)),
                ('ihr', models.CharField(blank=True, max_length=30)),
                ('sie', models.CharField(blank=True, max_length=30)),
                ('infinitive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjugator.Verb')),
            ],
        ),
        migrations.AddConstraint(
            model_name='conjugation',
            constraint=models.UniqueConstraint(fields=('infinitive', 'mood', 'tense'), name='unique_conjugation'),
        ),
    ]
