# Generated by Django 3.0 on 2019-12-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugator', '0006_auto_20191207_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('mood', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tense',
            fields=[
                ('mood', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
