# Generated by Django 3.0 on 2019-12-07 04:27

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('conjugator', '0008_auto_20191207_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tense',
            old_name='mood',
            new_name='tense',
        ),
    ]
