# Generated by Django 3.0 on 2019-12-08 06:36

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('conjugator', '0009_auto_20191207_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='mood',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tense',
            old_name='tense',
            new_name='name',
        ),
    ]
