# Generated by Django 3.0 on 2019-12-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugator', '0010_auto_20191208_0636'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conjugation',
            name='unique_conjugation',
        ),
        migrations.RenameField(
            model_name='conjugation',
            old_name='infinitive',
            new_name='verb',
        ),
        migrations.AddConstraint(
            model_name='conjugation',
            constraint=models.UniqueConstraint(fields=('verb', 'mood', 'tense'), name='unique_conjugation'),
        ),
    ]
