# Generated by Django 3.0 on 2019-12-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugator', '0011_auto_20191215_0701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verb',
            options={'ordering': ['frequency']},
        ),
    ]
